### ISSUE TITLE
KeyboardAwareFlatList scrolls to top when keyboard dissapears

### ISSUE THREAD

**Issue by manujbahl** [APSL/react-native-keyboard-aware-scroll-view#356]
I am using KeyboardAwareFlatList with multiline TextInput. When I click on the textInput the list scrolls up to bring the input in view. But when it disappears the list scrolls back to the top index instead of where it was before the keyboard showed

Anyone know how to make it remember its content offset

**Comment by durdevic** [comment]
Solved here https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/287#issuecomment-410798735

```enableResetScrollToCoords={false}``` might help the problem, while there are still issues with InputTexts which at the bottom of the View.

**Comment by bekatd** [comment]
Why is this issue closed. I am facing exactly same issue and `enableResetScrollToCoords={false}` does not fix it for me,

[www_screencapture_com_2022-9-29_20_49.webm](https://user-images.githubusercontent.com/6948919/193091102-5b92f1cb-3b60-4357-9a81-ae1461bda295.webm)
